# Generated by Django 5.2.1 on 2025-05-22 15:30

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-event_date", "facility"],
                "permissions": [
                    ("can_approve_booking", "Can approve or reject bookings"),
                    ("can_view_all_bookings", "Can see all bookings (not just own)"),
                ],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_maintain_facility", "Can add/edit/remove facilities")
                ],
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="attendees",
            field=models.PositiveIntegerField(
                default=1, help_text="Estimated number of attendees"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(
                blank=True, help_text="Any special arrangements needed"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this facility is available for booking"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event_date",
            field=models.DateField(
                help_text="Date of the event (cannot be in the past)",
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 22))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Nikah", "Nikah Ceremony"),
                    ("Religious Class", "Religious Class"),
                    ("Community Event", "Community Event"),
                    ("Funeral", "Funeral Service"),
                    ("Other", "Other Islamic Event"),
                ],
                default="Religious Class",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="facility",
            field=models.ForeignKey(
                help_text="Facility being booked",
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.facility",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("Fajr", "Fajr (Dawn)"),
                    ("Dhuhr", "Dhuhr (Noon)"),
                    ("Asr", "Asr (Afternoon)"),
                    ("Maghrib", "Maghrib (Sunset)"),
                    ("Isha", "Isha (Night)"),
                    ("Full Day", "Full Day Event"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                help_text="User who made this booking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the facility and its amenities"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(
                help_text="Name of the facility (e.g., Main Prayer Hall, Conference Room)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Hourly/daily rate in local currency",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
