# Generated by Django 5.2.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_event_date_payment_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(help_text='Date of the event (cannot be in the past)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special arrangements needed', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('05:00-07:00', '05:00 AM - 07:00 AM'), ('07:00-09:00', '07:00 AM - 09:00 AM'), ('09:00-11:00', '09:00 AM - 11:00 AM'), ('11:00-13:00', '11:00 AM - 01:00 PM'), ('13:00-15:00', '01:00 PM - 03:00 PM'), ('15:00-17:00', '03:00 PM - 05:00 PM'), ('17:00-19:00', '05:00 PM - 07:00 PM'), ('19:00-21:00', '07:00 PM - 09:00 PM'), ('21:00-23:00', '09:00 PM - 11:00 PM'), ('Full Day', 'Full Day (05:00 AM - 11:00 PM)')], max_length=20, verbose_name='Time Slot'),
        ),
    ]
