# Generated by Django 5.2.1 on 2025-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("08:00-10:00", "08:00 AM - 10:00 AM"),
                    ("10:00-12:00", "10:00 AM - 12:00 PM"),
                    ("12:00-14:00", "12:00 PM - 02:00 PM"),
                    ("14:00-16:00", "02:00 PM - 04:00 PM"),
                    ("16:00-18:00", "04:00 PM - 06:00 PM"),
                    ("18:00-20:00", "06:00 PM - 08:00 PM"),
                    ("20:00-22:00", "08:00 PM - 10:00 PM"),
                ],
                max_length=20,
                verbose_name="Time Slot",
            ),
        ),
    ]
