# Generated by Django 5.2.1 on 2025-06-16 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_booking_time_slot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-event_date", "facility"],
                "permissions": [
                    ("can_approve_booking", "Can approve or reject bookings"),
                    ("can_view_all_bookings", "Can see all bookings (not just own)"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_maintain_facility", "Can add/edit/remove facilities")
                ],
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="attendees",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="facility",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.facility",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("08:00-10:00", "08:00 AM - 10:00 AM"),
                    ("10:00-12:00", "10:00 AM - 12:00 PM"),
                    ("12:00-14:00", "12:00 PM - 02:00 PM"),
                    ("14:00-16:00", "02:00 PM - 04:00 PM"),
                    ("16:00-18:00", "04:00 PM - 06:00 PM"),
                    ("18:00-20:00", "06:00 PM - 08:00 PM"),
                    ("20:00-22:00", "08:00 PM - 10:00 PM"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="facility",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
