# Generated by Django 5.2.1 on 2025-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_booking_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ic_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Public", "Public")], max_length=10
            ),
        ),
    ]
