# Generated by Django 5.2.1 on 2025-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_userprofile_ic_number_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
