# Generated by Django 5.2.1 on 2025-06-23 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_auto_20250624_0030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
