# Generated by Django 5.2.1 on 2025-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_payment_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
