# Generated by Django 5.2.1 on 2025-06-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_alter_booking_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="special_requests",
        ),
    ]
