# Generated by Django 5.2.1 on 2025-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_alter_booking_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Nikah", "Nikah Ceremony"),
                    ("Religious Class", "Religious Class"),
                    ("Community Event", "Community Event"),
                    ("Seminar", "Seminar / Talk"),
                    ("Workshop", "Workshop / Training"),
                    ("Other", "Other Event"),
                ],
                default="Religious Class",
                max_length=30,
            ),
        ),
    ]
