# Generated by Django 5.2.1 on 2025-07-09 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_alter_booking_event_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={},
        ),
        migrations.AddField(
            model_name="facility",
            name="full_day_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Flat rate for full-day bookings (08:00-22:00)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rate per session (2 hours)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
